default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  primary:
    <<: *default
    database: meal_ideas_generator_development
  cache:
    <<: *default
    database: meal_ideas_generator_development_cache
    migrations_paths: db/cache_migrate
  queue:
    <<: *default
    database: meal_ideas_generator_production_queue
    migrations_paths: db/queue_migrate
  cable:
    <<: *default
    database: meal_ideas_generator_production_cable
    migrations_paths: db/cable_migrate

test:
  <<: *default
  database: meal_ideas_generator_test
  url: <%= ENV.fetch("DATABASE_URL") %>

production:
  primary: &primary_production
    <<: *default
    database: meal_ideas_generator_production
    username: meal_ideas_generator
    password: <%= ENV["MEAL_IDEAS_GENERATOR_DATABASE_PASSWORD"] %>
  cache:
    <<: *primary_production
    database: meal_ideas_generator_production_cache
    migrations_paths: db/cache_migrate
  queue:
    <<: *primary_production
    database: meal_ideas_generator_production_queue
    migrations_paths: db/queue_migrate
  cable:
    <<: *primary_production
    database: meal_ideas_generator_production_cable
    migrations_paths: db/cable_migrate
